Add aws_launch_configuration
snyk/driftctl pull request #1242
Opened 2021-11-26 16:14 UTC by sundowndev

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #959 
| ❓ Documentation  | yes

2021-12-01 15:33 UTC, wbeuil requested changes
Small comments on your PR.

In regards to the deep mode, by simply looking at the Terraform Read function in their source code I found and tested a special case where someone could add a user-data in 2 different ways:

```
resource "aws_launch_configuration" "foo" {
  name          = "foo"
  image_id      = "ami-0d718c3d715cec4a7"
  instance_type = "t3.micro"
  user_data_base64 = filebase64("script.sh")
}

resource "aws_launch_configuration" "bar" {
  name          = "bar"
  image_id      = "ami-0d718c3d715cec4a7"
  instance_type = "t3.micro"
  user_data = file("script.sh")
}
```

This will end up at the end of the analysis with false positives.

![image](https://user-images.githubusercontent.com/8110579/144263197-79f8d2ad-f638-43c6-abe2-de01b59fa066.png)

I also see that they fetch for root device (e.g. image below):

![image](https://user-images.githubusercontent.com/8110579/144263623-6b6155dd-1e59-4d81-a05e-e163c8d1f9eb.png)

I didn't test to find false positives in that regard but the chances are there are.

Maybe we should release this resource in non deep mode.

2021-12-02 14:51 UTC, sundowndev commented
@wbeuil Good catch! 

> Maybe we should release this resource in non deep mode.

You're right, I though it made sense to enable deep mode for this resource because you usually want to keep the template fully sync with your state. According to your tests there are too many edge cases we don't to deal with, I'll disable it.

2021-12-06 15:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/snyk/driftctl?pullRequest=1242) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/snyk/driftctl?pullRequest=1242) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/snyk/driftctl?pullRequest=1242) it.</sub>

2021-12-09 09:45 UTC, wbeuil submitted a review, later dismissed
LGTM

2021-12-09 11:14 UTC, wbeuil approved these changes

2021-12-09 13:14 UTC, merged