adding `humanReadableAttributes` to JSON output
snyk/driftctl pull request #1354
Opened 2022-02-17 22:42 UTC by wakeful

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #1325
| ❓ Documentation  | no

## Description

added `human_readable_attributes` field to json output e.q.
```json
{
    "id": "sgrule-1180062852",
    "type": "aws_security_group_rule",
    "human_readable_attributes": {
        "Destination": "0.0.0.0/0",
        "Ports": "All",
        "Protocol": "All",
        "SecurityGroup": "sg-08e4f811ab524c960",
        "Type": "egress"
    }
}
```

```json
{
    "id": "nacl-4081969105",
    "type": "aws_network_acl_rule",
    "human_readable_attributes": {
        "CIDR": "0.0.0.0/0",
        "Egress": "true",
        "Network": "acl-4f2eda2b",
        "Protocol": "All",
        "Rule number": "100"
    }
}
```

2022-02-17 22:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/snyk/driftctl?pullRequest=1354) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/snyk/driftctl?pullRequest=1354) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/snyk/driftctl?pullRequest=1354) it.</sub>

2022-02-19 06:45 UTC, sundowndev requested changes
Hi @wakeful thanks a lot for this PR 🙏🏻 

As per the example you provided and looking at the code, I can notice that the attributes are not parsed as JSON but returned in a single string instead. I don't think that's the right way to handle this, `humanReadableAttributes` should be an object instead. Also make sure to use snake-cased JSON keys (e.g. `human_readable_attributes`). Keep in mind that JSON output is intended to be used by other softwares for processing purposes.

I'll review further when comments will be addressed.

2022-02-19 12:31 UTC, wakeful commented
thanks for looking at this @sundowndev, I updated the PR base on your suggestions.

2022-02-21 08:14 UTC, moadibfr reviewed
Hi @wakeful. Thanks a lot for this PR !
I agree with @sundowndev and I think the revised version is better (especially I did not like having empty string when there was no human readable attributes).
I'm just wondering why do you need to change the case of the keys ?

2022-02-21 08:53 UTC, wakeful commented
hi @moadibfr, I started changing the key(s) name to keep it in the same `snake_case` form as the `partent` obj, also some of the extra attr are containing spaces, some are using `camelCase`.

e.q. outout without chaning the `case` on the key(s)
```json
{
"id": "sgrule-1180062852",
"type": "aws_security_group_rule",
"human_readable_attributes": {
	"Destination": "0.0.0.0/0",
	"Ports": "All",
	"Protocol": "All",
	"SecurityGroup": "sg-08e4f811ab524c960",
	"Type": "egress"
}},
{
"id": "rtbassoc-02bc8918dfcc806bd",
"type": "aws_route_table_association",
"human_readable_attributes": {
	"Table": "rtb-065a1aaa9b45900cf"
},
{
"id": "nacl-1588147895",
"type": "aws_network_acl_rule",
"human_readable_attributes": {
	"CIDR": "0.0.0.0/0",
	"Egress": "true",
	"Network": "acl-01d26c307d3b96d3e",
	"Protocol": "All",
	"Rule number": "100"
}}
```

2022-02-21 10:32 UTC, eliecharra commented
Thanks @wakeful for this very valuable PR and thanks a lot for @sundowndev and @moadibfr to handle that review 🙏🏻 
I agree with @moadibfr we probably do not want to change the case of the attributes, snake_case is the rule for the fixed fields in the JSON output but it's totally fine if we do not enforce anything for this dynamic part of the structure.

Can't wait to get it merged awesome work everyone ❤️

2022-02-21 10:47 UTC, moadibfr commented
> hi @moadibfr, I started changing the key(s) name to keep it in the same `snake_case` form as the `partent` obj (normalize), also some of the extra attr are containing spaces, some are using `camelCase`.

Yeah the point is that the key AND the value are supposed to be human readable and not really made to be processed that's why I was asking your use case. I think if at some point we'd like to have formatted key we should fixed the key instead of reformatting at the end.

2022-02-21 11:51 UTC, wakeful commented
@moadibfr, @eliecharra I reverted the dynamic change on the key, hopeflully this is ok now.

if you guys want I can `squash` the commits to reduce the amount of irrelevant `history`.

2022-02-21 13:04 UTC, moadibfr commented
> I figure maybe worth making sure we can parse the extra attr the same way, but I'm happy to revert that change :)

Yeah it sounds strange but it could make sens to have human readable attribute in the json output so a script/soft using this output could just display them to a human.

> if you guys want I can squash the commits to reduce the amount of irrelevant history.

I feel like 5 commit is a lot for this so I would be grateful if you could squash them yeah 🙇

2022-02-21 13:20 UTC, merged

2022-02-21 13:21 UTC, moadibfr commented
@all-contributors please add @wakeful for code